version: '3.1'
services:
  bole-server:
    restart: always
    image: harbor.yunlou.net.cn/bole/bole-server
    container_name: bole-server
    ports:
      - 8080:8080
    volumes:
      - logs/:/logs/
    environment:
      TZ: Asia/Shanghai